### ISSUE TITLE
Provide a documentation on how to use Pineapple

### ISSUE THREAD

**Issue by IterioDev** [charleywright/spotify-analyze-v2#3]
Hello,
First of all amazing work, finally someone putting in together something like this, as spotify's internal protocol is such a "mess". 
Been following your spotify-analyze-v2 repo for a while and it helped me understand quite a lot of stuff. I noticed recently that you've been actively working on a new project named "pineapple", i tried to run it paired with the desktop spotify app, setting the proxy to localhost:4070 (after also editing in main.rs), but all I get is "Error: invalid magic bytes" repeatedly.

Is this the expected result ATM?
Kind regards,
Iterio

**Comment by charleywright** [comment]
I've had a local version of the readme for a while now and have now pushed it, hopefully that clarifies a few things. This tool is in a very early stage of development, but if you'd still like to have a play with it I'd be happy to help get it working for you

**Comment by IterioDev** [comment]
Thanks a lot for the prompt reply & solutioning!
Definitely looks interesting, I have been trying to do something similar in C#, more like a simple proxy, without MITM (modifying) capabilities, and then trying to map each request & response to the protobuf definitions fed into the program.
Would love to have a play with this, so I can do some tinkering in C# afterwards and with some gpt magic help maybe convert code snippets and contribute to this.

EDIT: looking to tinker with this on windows, what would be the steps?

**Comment by charleywright** [comment]
Sent a friend request. It'll be interesting to dig into redirecting traffic on Windows as it's not something I've done before. Hopefully their slight coverage of Unix APIs lets us skirt around Win32 sockets :)
