### ISSUE TITLE
Read MercuryRequest response.

### ISSUE THREAD

**Issue by maximilianosinski** [charleywright/spotify-analyze-v2#5]
hey, would it be possible for you to add the responses from the MercuryRequests in the terminal.

because whenever a MercuryReq gets sent, the server sents back a response, would it be possible for you to add that the response gets displayed in the terminal?

**Comment by charleywright** [comment]
Did you get a `(recv) No handler for packet` message in your console? They should be handled, what were you doing in the app to cause one to be sent? I'll try to reproduce it now

EDIT: This is the response to a `hm://event-service/v1/events` `MercuryReq`
```
[RECV] [M] type=MercuryReq seq=1 parts=0 url=hm://event-service/v1/events
{
  "uri": "hm://event-service/v1/events",
  "statusCode": 200
}
Accepted event
```
