### ISSUE TITLE
[Feature Request] Show data types in MercuryReq.

### ISSUE THREAD

**Issue by maximilianosinski** [charleywright/spotify-analyze-v2#7]
Hey, could you add a update that shows the data types of the values in the MercuryReq payload?

something like this:
(string)12      (string)44      (string)80      (string)cdf62b56275c24ba3d0cd82a810486e47f234028        (string)91a81ef39f293f01cd3e34d688de38c9       (string)00000000000000000000000000000000        (string)track   (string)fwdbtn  (string)track   (string)trackdone       (string)2163084 (string)2163084 (string)116071  (string)116071  (string)116071  (string)124     (char)0       (char)0       (char)0       (char)0       (char)0       (char)0       (char)0       (char)0 ... and so on

**Comment by IterioDev** [comment]
Stop trying to make Spotify API bots, u are so blatantly obvious :D figure it out yourself

**Comment by charleywright** [comment]
These are not available in the payload and would have to be reverse engineered. I personally haven't looked into events at all but a pull request is always welcome!
