### ISSUE TITLE
What do these values mean and how to get them? (IOS)

### ISSUE THREAD

**Issue by maximilianosinski** [charleywright/spotify-analyze-v2#9]
So when using this analyzer on a iPhone you can see a systemInfo object when the spotify app starts in the MercuryAuth.

```
"systemInfo": {
 "cpuFamily": "CPU_ARM",
 "cpuExt": 12405,
 "os": "OS_IPHONE",
 "osVersion": 15,
 "osExt": 33032
 ...
}
```

what are the "cpuExt" values and "osExt" values, how to get them? how are they defined? i can't find anything on the web, maybe you know what it is.

**Comment by charleywright** [comment]
You would have to reverse the connection code and find where they come from. When I have time to start writing the wireshark dissector for pineapple I will probably reverse them but that could be in a few weeks
